Semana 6
KellyCarvalho/Logos pull request #10
Opened 2022-03-23 21:13 UTC by KellyCarvalho

2022-03-24 14:03 UTC, mariasantosdev commented on src/test/java/subCategory/SubCategoryDaoTest.java
> +                .doesNotContain("java", "go");
Poderia colocar uma descrição como null também, oque acha? :thinking:

2022-03-24 17:06 UTC, thaisandre requested changes

2022-03-24 17:06 UTC, thaisandre commented on src/main/java/Program.java
> +        writeHtml(courseDao.getAllPublic(), subcategoryDao.getAllActiveSubcategories(), subcategoryDao.getSubcategoriesWithoutDescription(), categoryDao.getAllActiveCategories());
você já chamou estes métodos anteriormente dentro do próprio `main()`, seria melhor chamar apenas uma vez para evitar várias idas ao banco de dados. ou seja, você pegaria os dados apenas uma vez para imprimir os logs e para gerar o relatório (***request changed**)

2022-03-24 17:06 UTC, thaisandre commented on src/test/java/subCategory/SubCategoryDaoTest.java
> +                .doesNotContain("java", "go");
esta aqui é ***request changed** !

2022-03-24 17:06 UTC, thaisandre commented on src/main/java/Logos/category/CategoryDTO.java
>      }
deletar esta classe (***request changed**)

2022-03-24 17:06 UTC, thaisandre commented on src/main/java/Logos/subCategory/SubCategoryDTO.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
na verdade, pŕecisa deletar esta classe que é utilizada em outra classe que não está sendo utilizada (***request changed**)

2022-03-24 19:21 UTC, mariasantosdev commented on src/main/java/Logos/utils/GenerateHtml.java
> +                </html>
ótimo ponto!

2022-03-24 23:08 UTC, mariasantosdev commented on src/main/java/Logos/utils/builder/CourseBuilder.java
> +    private String courseProgramDescription;
Não precisa por  courseProgramDescription pois você já está dentro de do contexto de Course

2022-03-24 23:08 UTC, mariasantosdev commented on src/main/java/Logos/utils/builder/CourseBuilder.java
> +    private String courseProgramDescription;
Não precisa por  courseProgramDescription pois você já está dentro de do contexto de Course

2022-03-24 23:12 UTC, mariasantosdev approved these changes

2022-03-25 10:58 UTC, thaisandre requested changes

2022-03-25 10:58 UTC, thaisandre commented on src/main/java/Logos/activity/Video.java
> +
pode tirar esta quebra de linha para manter o padrão dos demais construtores vazios do projeto (***request changed**)

2022-03-25 10:58 UTC, thaisandre commented on src/main/java/Logos/alternative/Alternative.java
> +
pode tirar esta quebra de linha para manter o padrão dos demais construtores vazios do projeto (***request changed**)

2022-03-25 10:58 UTC, thaisandre commented on src/main/java/Logos/utils/builder/CourseBuilder.java
> +    private String courseProgramDescription;
e o ideal é manter o mesmo nome dos atributos da classe `Course` (***request changed**)

2022-03-25 10:58 UTC, thaisandre commented on src/main/java/Program.java
> +        writeHtml(courseDao.getAllPublic(), subcategoryDao.getAllActiveSubcategories(), subcategoryDao.getSubcategoriesWithoutDescription(), categoryDao.getAllActiveCategories());
faltou arrumar este aqui

2022-03-25 18:45 UTC, thaisandre requested changes

2022-03-25 18:45 UTC, thaisandre commented on src/main/java/Logos/utils/builder/CourseBuilder.java
> +    private String courseProgramDescription;
Kelly, o que a Madu quis dizer aqui é que você não precisa referenciar *course* no nome do atributo `courseProgramDescription` para evitar redundância - já que ele está dentro de uma classe que já contém a palavra *course* no nome. 

e o que eu quis dizer no meu cometário é que o mesmo vale para a classe `Course` - e geralmente mantemos os mesmos nomes de atributos na classe de modelo dentro do seu respectivo *builder*. o melhor seria chamar este atributo de apenas `description` tanto em `Course` como em `CourseBuilder`, o que acha?

2022-03-25 18:45 UTC, thaisandre commented on src/main/java/Program.java
> +        writeHtml(courseDao.getAllPublic(), subcategoryDao.getAllActiveSubcategories(), subcategoryDao.getSubcategoriesWithoutDescription(), categoryDao.getAllActiveCategories());
ainda faltou arrumar este ***request changed** aqui. ainda vai duas vezes buscar os dados sendo que só precisa ir uma vez. se tiver dúvida, pode me chamar

2022-03-25 19:40 UTC, thaisandre requested changes

2022-03-25 19:40 UTC, thaisandre commented on src/main/java/Logos/course/Course.java
> +    }
este método não está sendo utilizado, pode jogar fora (***request changed**)

2022-03-25 19:40 UTC, thaisandre commented on src/main/java/Logos/course/Course.java
> +    }
estes métodos também não estão sendo utilizados, pode jogar fora (*request changed)
além disso não deveriam retorna `Object`

2022-03-25 19:40 UTC, thaisandre commented on src/main/java/Logos/course/Course.java
> +                "courseProgramDescription='" + description + '\n' +
faltou mudar o nome do lado esquerdo, deveria ser `description = description" (***request changed**)

2022-03-25 19:40 UTC, thaisandre commented on src/main/java/Logos/subCategory/SubCategory.java
>      }
este método não está sendo utilizado, pode jogar fora (***request changed**)

2022-03-25 19:40 UTC, thaisandre commented on src/main/java/Logos/category/Category.java
>      }
este método não está sendo utilizado, pode jogar fora (***request changed**)

2022-03-25 19:40 UTC, thaisandre commented on src/main/java/Program.java
> +        List<Course> PublicCourses = courseDao.getAllPublic();
variáveis no Java sempre iniciam com letra minúscula (convenção) - o correto seria `publicCourses`(***request changed**)

2022-03-25 19:41 UTC, thaisandre commented
@KellyCarvalho ainda faltou mudar no script da modelagem do banco:

```
CREATE TABLE `Course`(
`id` BIGINT  PRIMARY KEY AUTO_INCREMENT,
`name` VARCHAR(255) NOT NULL,
`identifier_code` VARCHAR(255) UNIQUE NOT NULL,
`estimated_time` INT,
`visibility`BOOLEAN DEFAULT FALSE,
`target_audience` VARCHAR(255),
`instructor_name` VARCHAR(255) NOT NULL,
`course_program_description` TEXT,
`developed_skills` TEXT,
`fk_subcategory`  BIGINT NOT NULL,
FOREIGN KEY(`fk_subcategory`) REFERENCES `Subcategory`(`id`)
);
```

Note que ainda está como `course_program_description` e não vai funcionar

2022-03-25 19:42 UTC, thaisandre commented
além disso, você pode jogar a classe `ConnectionFactory` fora já que não está mais sendo utilizada. (acabei não pegando isso antes)

2022-03-25 20:16 UTC, thaisandre requested changes

2022-03-25 20:16 UTC, thaisandre commented on src/main/java/Logos/utils/builder/CourseBuilder.java
> +    }
este método deveria se chamar `withDescription()` e receber um parâmetro chamado `description` (***request changed**)

2022-03-25 20:16 UTC, thaisandre commented on src/main/java/Program.java
> +        System.out.println(activeCategories);
deveria imprimir apenas os nomes de cada modelo para facilitar a leitura no console como esta antes

2022-03-25 20:40 UTC, thaisandre approved these changes

2022-03-25 20:45 UTC, merged