Semana 8
KellyCarvalho/Logos pull request #12
Opened 2022-04-07 21:02 UTC by KellyCarvalho

2022-04-09 20:10 UTC, thaisandre requested changes

2022-04-09 20:10 UTC, thaisandre commented on src/main/java/br/com/logos/commonValidator/ErrorValidationHandler.java
> +    }
qual o motivo de criar este handler aqui? não temos nenhuma requisição POST para uma api. pode apagar porque não vai ser chamado em nenhum fluxo no estado que está o projeto (***request changed**)

2022-04-09 20:10 UTC, thaisandre commented on src/main/java/br/com/logos/commonValidator/FormErrorDTO.java
> +}
depois que apagar o `ErrorValidationHandler`, pode apagar este cara (***request changed**)

2022-04-09 20:10 UTC, thaisandre commented on src/main/java/br/com/logos/category/CategoryListDTO.java
> +    }
apenas sugestão: o construtor poderia receber apenas uma `category` e atribuir os valores dos atributos chamando os getters da category

2022-04-09 20:10 UTC, thaisandre commented on src/main/java/br/com/logos/category/CategoryListDTO.java
> +        });
sugestão: se o construtor recebesse apenas uma category a chamada ficaria mais simples: `categoriesDto.add(new CategoryListDTO(category))`;

2022-04-09 20:10 UTC, thaisandre commented on src/main/java/br/com/logos/category/CategoryListDTO.java
> +        });
o mesmo vale para os outros dtos de `SubCategory` e `Course`

2022-04-10 01:54 UTC, mariasantosdev commented on src/main/webapp/WEB-INF/views/category/formInsertCategory.jsp
> +            <form:input  path="colorCode" placeholder="por exemplo #fcc14a" class="form-control" id="colorCode" type="text" name="colorCode"/>
opcional - Da para colocar o type do input como color assim como colocou nas semanas passadas!!

2022-04-10 01:59 UTC, mariasantosdev commented
Kelly também seria interessante que o status da categoria aparecesse em português (esta em português no protótipo inserido no card) :eyes: 

![image](https://user-images.githubusercontent.com/75762013/162597944-0c05bd03-b28c-4707-8bda-dfc527d566b6.png)

Se precisar de ajuda para fazer pode me pingar :heart:

2022-04-10 12:57 UTC, KellyCarvalho commented on src/main/java/br/com/logos/category/CategoryAdminController.java
> +    public String viewFormInsertCategory(CategoryInsertDTO categoryInsertDTO, BindingResult result, Model model) {
Eu preciso dele pra poder exibir os erros quando tem no insert

2022-04-10 14:33 UTC, KellyCarvalho commented on src/main/java/br/com/logos/category/CategoryInsertDTO.java
> +    private String imageUrl;
a url não é obrigatória estava procurando um pattern pra aceitar apenas url ou vazio, mas ainda estou testando

2022-04-10 14:36 UTC, KellyCarvalho commented on src/main/java/br/com/logos/category/CategoryListDTO.java
> +    private List<SubCategoryDTO> subCategories;
Mas neste caso a subcategoria pode ser vazia por não ter nenhuma sub atrelada a ela, a dependência é ao contrário, uma subcategoria preciso de uma categoria ou entendi errado?

2022-04-10 14:37 UTC, KellyCarvalho commented on src/main/java/br/com/logos/category/CategoryUpdateDTO.java
> +    private String imageUrl;
Estou procurando uma regex porque a URL não é obrigatória

2022-04-10 15:11 UTC, mariasantosdev commented on src/main/java/br/com/logos/category/CategoryAdminController.java
> +    public String viewFormInsertCategory(CategoryInsertDTO categoryInsertDTO, BindingResult result, Model model) {
aah achei que somente o BindingResult já seria o suficiente para isso :thinking:

2022-04-10 15:18 UTC, mariasantosdev commented on src/main/java/br/com/logos/category/CategoryListDTO.java
> +    private List<SubCategoryDTO> subCategories;
hmm verdade Kelly, está certissima eu que fiz confusão haha, desculpe!! é ao contrário mesmo

2022-04-10 15:20 UTC, mariasantosdev commented on src/main/java/br/com/logos/category/CategoryUpdateDTO.java
> +    private String imageUrl;
essa anotação faz a regex mesmo para você mas como você não quer inserir imagens apenas por url como por exemplo:
https://www.alura.com.br/assets/api/formacoes/categorias/devops.svg ai não serve :c

2022-04-10 15:54 UTC, thaisandre commented on src/main/java/br/com/logos/category/CategoryAdminController.java
> +    public String viewFormInsertCategory(CategoryInsertDTO categoryInsertDTO, BindingResult result, Model model) {
realmente, a Madu tem razão, não precisa já que vocẽ não está utilizando

2022-04-10 15:58 UTC, thaisandre approved these changes

2022-04-11 12:32 UTC, mariasantosdev approved these changes

2022-04-11 12:33 UTC, merged