Semana 10
KellyCarvalho/Logos pull request #14
Opened 2022-04-20 22:04 UTC by KellyCarvalho

2022-04-25 12:56 UTC, mariasantosdev commented on src/main/java/br/com/logos/course/CourseController.java
> +        return "redirect:/admin/courses/" + possibleCourse.get().getCategoryCode()+ "/" + possibleCourse.get().getSubCategoryCode();
Você já tem os códigos da categoria, subcategoria e curso pois recebe eles lá na linha 87

2022-04-25 12:56 UTC, mariasantosdev commented on src/main/java/br/com/logos/subCategory/SubCategoryController.java
> +        return  "redirect:/admin/subcategories/"+possibleSubCategory.get().getCategoryCode();
Kelly aqui também poderia passar direto o `subcategoryCode` que você recebe na 71

2022-04-25 12:56 UTC, mariasantosdev commented on src/main/java/br/com/logos/subCategory/SubCategoryRepository.java
> +            order by s.position
Aqui você poderia seguir o padrão de colocar todos os comandos do sql com letras maiúsculas pois você começou fazendo dessa forma no começo da query

2022-04-25 12:56 UTC, mariasantosdev commented on src/main/java/br/com/logos/subCategory/SubCategoryRepository.java
> +            order by s.position
getAllByCategoryOrderByPosition** pois você está ordenando pelo campo `position`

2022-04-25 12:56 UTC, mariasantosdev commented on src/main/java/br/com/logos/subCategory/SubCategoryRepository.java
> +            and c.visibility = true
Provavelmente esse filtro nem está funcionando né Kelly? por conta daquele probleminha que vimos no review sincrono com as projections e tudo :eyes:, acho que vale a pena testar e se realmente não estiver filtrando deleta da query e deixa para ordenar somente no java mesmo

2022-04-25 12:56 UTC, mariasantosdev commented on src/main/java/br/com/logos/user/User.java
> +    }
realmente precisa dos setters? aqui mostra que não estão sendo usados

2022-04-25 12:56 UTC, mariasantosdev commented on src/main/java/br/com/logos/user/profile/Profile.java
> +        return name;
precisa desses getters e setters?

2022-04-25 12:56 UTC, mariasantosdev commented on src/main/webapp/WEB-INF/views/category/categoriesList.jsp
> +                                <a class="button_" href="/admin/categories/${category.code}">
Kelly geralmente colocamos o nome da classe sem esse `_` no final, geralmente usamos ele para separar palavras como por exemplo: `delete_button` mas como não é o caso eu removeria ele

2022-04-25 12:56 UTC, mariasantosdev commented on src/main/webapp/WEB-INF/views/course/formInsertCourse.jsp
> +        </section>
poderia pular uma linha aqui também(já que você escolheu seguir esse padrãozinho de ir pulando linha)

2022-04-25 12:56 UTC, mariasantosdev commented on src/main/webapp/WEB-INF/views/course/formUpdateCourse.jsp
> +        </section>
poderia pular uma linha aqui também!!

2022-04-25 12:56 UTC, mariasantosdev commented on src/main/webapp/WEB-INF/views/publicPageCategory/publicPageCategoryList.jsp
> +        <title>Programação | Cursos online de tecnologia</title>
poderia ser dinamico  essa primeira parte do titulo que informa o nome da cateoria né: :eyes:

2022-04-25 12:56 UTC, mariasantosdev commented on src/main/webapp/assets/css/form.css
> +}
Apenas curiosidade: Porque você optou em usar o id ao invés de classes?

2022-04-25 12:56 UTC, mariasantosdev commented on utilsFiles/database/data.sql
> +insert into User (name, email, password) values ('teste', 'teste@gmail.com','$2a$10$fCijSt.rHvs9hxkHQn3lDe1ZQgmP4ywJjfvJiQWgCNYz95BBHWTKq');
Nesse arquivo inteiro você segue o padrão de colocar os comandos SQL em letra maiúsculas, então acho interessante manter nesse insert também

2022-04-25 12:56 UTC, mariasantosdev commented on utilsFiles/database/dataDefinition.sql
> +    `user_id`    BIGINT,
Kelly você não defeniu a PK dessa tabela que seria tipo assim: `PRIMARY KEY(user_id, profiles_id)`

2022-04-25 12:56 UTC, mariasantosdev commented on src/main/java/br/com/logos/LogosApplication.java
> +@EnableSpringDataWebSupport
Kelly senão me engano essa anotação não precisa mais nas ultimas versões (testei sem aqui e o projeto subiu normal), se quiser remover e dar uma testada melhor ai :eyes:

2022-04-25 13:24 UTC, thaisandre requested changes

2022-04-25 13:24 UTC, thaisandre commented on src/main/java/br/com/logos/LogosApplication.java
> +@EnableSpringDataWebSupport
esta anotação `@EnableSpringDataWebSupport` não é necessária (***request changed**)

2022-04-25 13:24 UTC, thaisandre commented on src/main/java/br/com/logos/category/CategoryRepository.java
> +            join s.courses co
esses dois *joins* não são necessários (***request changed**)

2022-04-25 13:24 UTC, thaisandre commented on src/main/java/br/com/logos/config/security/SecurityConfiguration.java
> +                .antMatchers("/admin/**").authenticated()
funciona da maneira que está, mas é de costume ordenarmos do mais restrito para o mais aberto, ou seja, aquilo que exige autenticação vem primeiro:

```
.antMatchers("/admin/**").authenticated()
.antMatchers("/api/categories").permitAll()
.antMatchers("/bGltcGEtby1jYWNoZS1kYS1hcGktYWU").permitAll()
```

2022-04-25 13:24 UTC, thaisandre commented on src/main/java/br/com/logos/config/swagger/SwaggerConfigurations.java
> +                .paths(PathSelectors.ant("/**"))
sugestão: poderia também restringir apenas para os endpoints que comecem com "/api": `/api/**`

2022-04-25 13:24 UTC, thaisandre commented on src/main/java/br/com/logos/course/CourseUpdateDTO.java
> +        this.subCategory = getSubCategory();
cuidado, aqui deveria ser: (***request changed**)

```
    this.subCategory = course.getSubCategory();
```

2022-04-25 13:24 UTC, thaisandre commented on src/main/java/br/com/logos/subCategory/SubCategoryRepository.java
> +            order by s.order
lembra que você está utilizando o ` @Value("#{target.courses}")` dentro da projection e ele não vai considerar essas filtragens por curso da query já que o Spring Data vai fazer um *select* apenas para pegar os cursos de cada subcategoria e você fez o método `getActiveSubCategoriesWithPublicCourse()` lá para filtrar exatamente isso. então este *join* com a tabela `course` é desnecessário (***request changed**)

2022-04-25 13:24 UTC, thaisandre commented on src/main/webapp/assets/css/form.css
> +}
tem momentos que você utiliza classe e outros o id como seletor no css. no css é mais comum utilizar classe. modificar para utilizar classe para manter o padrão (***request changed**)

2022-04-25 13:24 UTC, thaisandre commented on src/main/webapp/assets/css/listPage.css
> +}
mesmo aqui: utilizar classe ao invés do id (***request changed**)

2022-04-25 13:24 UTC, thaisandre commented on src/main/java/br/com/logos/course/CourseController.java
> +        return "redirect:/admin/courses/" + possibleCourse.get().getCategoryCode()+ "/" + possibleCourse.get().getSubCategoryCode();
sugestão:

```
return "redirect:/admin/courses/" + category + "/" + subcategory;
```

2022-04-25 13:24 UTC, thaisandre commented on pom.xml
> +		</dependency>
aqui é melhor utilizar a única dependência do security pelo *starter* do Spring Boot que vai conter tudo que precisa: (***request changed**)

```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-security</artifactId>
</dependency>
```

2022-04-25 14:32 UTC, KellyCarvalho commented on src/main/java/br/com/logos/course/CourseController.java
> +        return "redirect:/admin/courses/" + possibleCourse.get().getCategoryCode()+ "/" + possibleCourse.get().getSubCategoryCode();
categoria ok, mas por exemplo eu posso mudar a subcategoria, então não vai ser o mesmo código que passei por parâmetro, ou to me confundindo?

2022-04-25 14:34 UTC, KellyCarvalho commented on src/main/java/br/com/logos/course/CourseController.java
> +        return "redirect:/admin/courses/" + possibleCourse.get().getCategoryCode()+ "/" + possibleCourse.get().getSubCategoryCode();
A categoria neste caso vai ser estático mesmo não precisa, mas a subcategoria pode mudar, então o ideal não seria deixar dinâmico?

2022-04-25 14:35 UTC, KellyCarvalho commented on src/main/java/br/com/logos/course/CourseController.java
> +        return "redirect:/admin/courses/" + possibleCourse.get().getCategoryCode()+ "/" + possibleCourse.get().getSubCategoryCode();
![image](https://user-images.githubusercontent.com/52672075/165111270-b2c4fd7d-9bb8-4912-a6a1-6cb0b24585b6.png)

2022-04-25 14:37 UTC, KellyCarvalho commented on src/main/java/br/com/logos/subCategory/SubCategoryController.java
> +        return  "redirect:/admin/subcategories/"+possibleSubCategory.get().getCategoryCode();
![image](https://user-images.githubusercontent.com/52672075/165111657-74c47148-9fc1-4857-9a28-928a6f91b021.png)

Mesma situação, eu posso querer mudar a categoria portanto não vai ser a mesma do parâmetro, ou estou me confundindo?

2022-04-25 15:00 UTC, KellyCarvalho commented on src/main/java/br/com/logos/subCategory/SubCategoryRepository.java
> +            order by s.position
no banco o nome da coluna é Position, mas no java o nome é Order, eu uso position(nome definido no banco) mesmo neste caso?

2022-04-25 15:14 UTC, KellyCarvalho commented on src/main/java/br/com/logos/subCategory/SubCategoryRepository.java
> +            and c.visibility = true
de fato este filtro não tá funcionando

2022-04-25 15:28 UTC, KellyCarvalho commented on src/main/webapp/assets/css/form.css
> +}
pensei em fazer um elemento com um estilo único pra cada, mas acabou que não faz sentido agora, irei trocar pra classes

2022-04-25 19:34 UTC, KellyCarvalho commented on src/main/java/br/com/logos/category/CategoryRepository.java
> +            join s.courses co
eu fiz alguns testes e se eu não fizer eles vai retornar as categorias ativas com subcategorias desativadas que tem curso público
![image](https://user-images.githubusercontent.com/52672075/165160999-28329213-bcdb-417a-bae9-28758d934553.png)
Assim ele filtra bem e funciona, o que não funciona é apenas a lista de subcategorias que tenho que fazer a filtragem e ordenação pelo java

2022-04-25 19:44 UTC, KellyCarvalho commented on src/main/java/br/com/logos/subCategory/SubCategoryRepository.java
> +            order by s.order
Retirei o join de cursos e retornou subcategoria sem cursos
![image](https://user-images.githubusercontent.com/52672075/165162551-f9f6adb5-7039-4510-8841-3c485d8a096d.png)

2022-04-25 19:51 UTC, KellyCarvalho commented on src/main/java/br/com/logos/course/CourseController.java
> +        return "redirect:/admin/courses/" + possibleCourse.get().getCategoryCode()+ "/" + possibleCourse.get().getSubCategoryCode();
para a categoria tudo bem ser o parametro da url que neste caso é estática, mas a subcategoria eu posso mudar então deve ser dinâmica de acordo ao que eu colocar como subcategoria
![image](https://user-images.githubusercontent.com/52672075/165164088-4c44980c-13c6-4475-b153-45ab31ffe16b.png)

2022-04-26 13:35 UTC, thaisandre commented on src/main/java/br/com/logos/subCategory/SubCategoryRepository.java
> +            order by s.order
boa, tem razão!

2022-04-26 13:38 UTC, thaisandre approved these changes

2022-04-26 16:24 UTC, mariasantosdev commented on src/main/java/br/com/logos/category/CategoryRepository.java
> +            AND co.visibility = true
esses filtros não estão funcionando certo? então bora remover porque senão uma outra pessoa que visse a query poderia achar que de fato ela faz esses filtros

2022-04-26 16:24 UTC, mariasantosdev commented on src/main/java/br/com/logos/user/User.java
> +    }
Kelly não precisa desses getters e setter né?

2022-04-26 16:27 UTC, mariasantosdev commented
Kelly estava dando uma olhada aqui em um método da classe CategoryInsertDTO que deixamos passar :eyes: 
![image](https://user-images.githubusercontent.com/75762013/165347779-95a7403c-1641-46f3-801a-220d5315b446.png)

Você passa a CategoryInsertDTO mas você já está dentro dela então você poderia usar o this e parar de receber CategoryInserDto ficaria semelhante ao que foi feito no CourseInsetDTO dessa semana

2022-04-26 16:29 UTC, mariasantosdev commented on src/main/java/br/com/logos/course/CourseController.java
> +        return "redirect:/admin/courses/" + possibleCourse.get().getCategoryCode()+ "/" + possibleCourse.get().getSubCategoryCode();
Boa Kelly!! eu achei que ia ter como :c, mas então está certissimo

2022-04-26 16:29 UTC, mariasantosdev commented on src/main/java/br/com/logos/subCategory/SubCategoryRepository.java
> +            order by s.position
ah simm faz sentido!! nesse caso ambos acho semantico, pode manter esse nome se quiser tranquilo!!

2022-04-26 16:31 UTC, mariasantosdev commented on src/main/webapp/assets/css/form.css
> +}
Boa acho melhor!! eu prefiro trabalhar com id mais com js(dependendo do caso também) e quando tenho que "sobrescrever" uma propriedade defenida pela classe, pois a "força" que o id tem é maior que a classe

2022-04-26 16:33 UTC, KellyCarvalho commented on src/main/java/br/com/logos/category/CategoryRepository.java
> +            AND co.visibility = true
Esses funcionam sim, os filtros só não funcionam pra lista de subcategorias por exemplo, mas se eu retirar eles vai me retornar registros que não quero e precisarei fazer um filtro pela jsp ou pelo java

2022-04-27 14:12 UTC, mariasantosdev approved these changes

2022-04-27 14:16 UTC, merged