Semana 3
KellyCarvalho/Logos pull request #7
Opened 2022-03-02 20:54 UTC by KellyCarvalho

2022-03-02 21:16 UTC, thaisandre requested changes

2022-03-02 21:16 UTC, thaisandre commented on src/Logos/category/Category.java
> +        return categories.stream().filter(category -> category.isActive()).toList();
apenas sugestão: 

poderia utilizar *method reference*:

```java
categories.stream().filter(Category::isActive).toList();
```

2022-03-02 21:16 UTC, thaisandre commented on src/Logos/subCategory/SubCategory.java
> +        return subCategories.stream().filter(subCategory -> subCategory.isEmptyDescription()).toList();
apenas sugestão:

poderia utilizar *method reference*:
```java
subCategories.stream().filter(SubCategory::isEmptyDescription).toList();
```

2022-03-02 21:16 UTC, thaisandre commented on src/Logos/subCategory/SubCategory.java
> +        return this.status.equals(CategoryStatus.ACTIVE) ? true : false;
aqui não precisa deste ternário já que o método `equals()` retorna um boolean. e seria interessante inverter a ordem de comparação para evitar `NullPointerException`: (***request changed**)

```java
public boolean isActive() {
    return CategoryStatus.ACTIVE.equals(this.status);
}
```

2022-03-02 21:16 UTC, thaisandre commented on src/Logos/subCategory/SubCategory.java
> +        return this.getDescription().isEmpty() || this.getDescription().isBlank() ? true : false;
mesma coisa aqui, não precisa do ternário já que o método `equals()` retorna um booleando. e também está quebrando o contrato do card, era apenas para ver se é vazio, então pode tirar a parte que usa o `isBlank()`: (***request changed**)

```java
public boolean isEmptyDescription() {
    return this.description.isEmpty();
}

2022-03-02 21:16 UTC, thaisandre commented on src/Logos/subCategory/SubCategory.java
> +        return subCategories.stream().filter(subCategory -> !subCategory.isEmptyDescription()).map(subCategory -> subCategory.isActive()).count();
aqui não precisa utilizar o map já que no final você dá um `count()`. poderia ser dois *filters*: (***request changed**)

```java
public static Long getQuantitySubCategoriesActivesWithDescription(List<SubCategory> subCategories) {
    return subCategories.stream().filter(subCategory -> !subCategory.isEmptyDescription()).filter(SubCategory::isActive).count();
```

2022-03-02 21:21 UTC, KellyCarvalho commented on src/Logos/subCategory/SubCategory.java
> +        return subCategories.stream().filter(subCategory -> subCategory.isEmptyDescription()).toList();
Não funcionou

2022-03-02 21:31 UTC, KellyCarvalho commented on src/Logos/subCategory/SubCategory.java
> +        return subCategories.stream().filter(subCategory -> !subCategory.isEmptyDescription()).map(subCategory -> subCategory.isActive()).count();
Assim ele me retorna zerado, só funcionou com o map, eu tinha tentado fazer apenas com um predicado ou com o filter sempre retorna zerado

2022-03-02 21:38 UTC, thaisandre commented on src/Logos/subCategory/SubCategory.java
> +        return subCategories.stream().filter(subCategory -> !subCategory.isEmptyDescription()).map(subCategory -> subCategory.isActive()).count();
boa, Kelly, achei que funcionaria com filter. deixa map mesmo

2022-03-02 21:39 UTC, thaisandre approved these changes

2022-03-02 21:39 UTC, thaisandre commented
boa, Kelly! show de bola! parabéns!

2022-03-03 02:28 UTC, mariasantosdev commented on src/Logos/category/Category.java
> +        return this.getStatus().equals(CategoryStatus.ACTIVE);
Agora que vi que a Thais havia feito exatamente o mesmo comentário na classe SubCategory :laughing:

2022-03-03 14:04 UTC, mariasantosdev approved these changes

2022-03-03 14:06 UTC, merged