Semana 4
KellyCarvalho/Logos pull request #8
Opened 2022-03-10 02:02 UTC by KellyCarvalho

2022-03-10 12:29 UTC, mariasantosdev requested changes

2022-03-10 12:29 UTC, mariasantosdev commented on src/main/java/Logos/commonValidator/StringValidator.java
> +    public static boolean isValidCodeWithoutNumbers(String code, String message) {
eu sinceramente preferia o nome antigo desse método que se chamava `isValidCode` isso porque eu li o nome desse como `isValidCodeWithoutNumbers` e depois vi que a regex também não aceitava caracteres especiais (exceto o `-`).
Então o nome dessa forma acabou não informando exatamente oque esse método faz

2022-03-10 12:29 UTC, mariasantosdev commented on src/main/java/Logos/commonValidator/StringValidator.java
> +    public static boolean isValidCodeWithoutNumbers(String code, String message) {
oque acha @thaisandre?

2022-03-10 12:29 UTC, mariasantosdev commented on src/main/java/Logos/subCategory/SubCategory.java
> +        return this.getDescription()!=null? this.getDescription().isEmpty():false;
Que tal `this.getDescription() != null && this.getDescription().isEmpty();`? [Apenas sugestão] para uma melhoria de leitura

2022-03-10 12:29 UTC, mariasantosdev commented on src/main/java/Logos/utils/GenerateSql.java
> +    //TODO trocar nome pra write insert e o nome
foi feito? mudou de ideia sobre fazer? se sim já pode deletar os comentários

2022-03-10 12:29 UTC, mariasantosdev commented on src/test/java/CategoryTest.java
> +                });
Apenas sugestão: remover as chaves assim como fez nos outros métodos

2022-03-10 12:29 UTC, mariasantosdev commented on src/test/java/CategoryTest.java
> +                });
remover as chaves aqui também se quiser

2022-03-10 13:27 UTC, KellyCarvalho commented on files/database/modelingScript.sql
> +`status` VARCHAR(255), -- trocar para enum
Sim, mas já alterei

2022-03-10 13:36 UTC, KellyCarvalho commented on files/database/modelingScript.sql
> +`correct` BOOLEAN, -- Testar o valor default
DEFAULT é null, então coloquei o default como false já configurado

2022-03-10 13:37 UTC, mariasantosdev requested changes

2022-03-10 13:37 UTC, mariasantosdev commented on src/test/java/CourseTest.java
> +                });
pode remover as chaves

2022-03-10 13:37 UTC, mariasantosdev commented on src/test/java/CourseTest.java
> +                });
pode remover as chaves

2022-03-10 13:37 UTC, mariasantosdev commented on src/test/java/CourseTest.java
> +        });
pode remover as chaves

2022-03-10 13:37 UTC, mariasantosdev commented on src/test/java/CourseTest.java
> +        new Course("Java", "java", 10, instructorName, subCategory);
esse teste não tem assert :thinking:

2022-03-10 13:43 UTC, KellyCarvalho commented on src/main/java/Logos/category/Category.java
> +    //TODO colocar num service
Feito

2022-03-10 13:44 UTC, KellyCarvalho commented on src/main/java/Logos/category/Category.java
> +    public String getStudyGuide() {
para test mas já irei retirar

2022-03-10 13:45 UTC, KellyCarvalho commented on src/main/java/Logos/commonValidator/StringValidator.java
> +    public static boolean isValidCodeWithoutNumbers(String code, String message) {
A regex dele é diferente pois é pra Category e SubCategory

2022-03-10 14:05 UTC, mariasantosdev requested changes

2022-03-10 14:05 UTC, mariasantosdev commented on src/test/java/SubCategoryTest.java
> +        assertTrue(getQuantitySubCategoriesActivesWithDescription(subCategories) == sizeExpected);
daria para simplificar fazendo um assertEquals né? (apenas sugestão)

2022-03-10 14:17 UTC, mariasantosdev commented on src/main/java/Logos/commonValidator/StringValidator.java
> +    public static boolean isValidCodeWithoutNumbers(String code, String message) {
entendi...Acho justo Kelly mas comentei mais porque acho que o nome não tras a informação completa sabe? pois nessa regex você valida sem números e também sem caracteres especiais certo? e no nome do método só deixa claro a parte de sem números....mas acho que pode manter assim mesmo

2022-03-10 14:27 UTC, thaisandre commented on src/main/java/Logos/commonValidator/StringValidator.java
> +    public static boolean isValidCodeWithoutNumbers(String code, String message) {
concordo com a Madu

2022-03-10 15:02 UTC, thaisandre requested changes

2022-03-10 16:40 UTC, mariasantosdev commented on files/database/modelingScript.sql
> +`category_description` TEXT,
Não precisa colocar category na frente, essa é uma coluna da tabela Category então fica claro que é a descrição da categoria

2022-03-10 16:41 UTC, mariasantosdev commented on files/database/modelingScript.sql
> +`subcategory_description` TEXT,
Não precisa colocar subcategory na frente

2022-03-10 16:42 UTC, mariasantosdev commented on files/database/modelingScript.sql
> +`explanation_description` TEXT NOT NULL,
Não precisa por explanation na frente

2022-03-10 16:59 UTC, mariasantosdev commented on files/database/modelingScript.sql
> +`id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
Não é necessário colocar NOT NULL na coluna que foi declarada com PRIMARY KEY ela já é NOT NULL e além disso UNIQUE
https://www.mysqltutorial.org/mysql-primary-key/

2022-03-10 17:00 UTC, mariasantosdev commented on files/database/modelingScript.sql
> +`id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
Vale para todas as tabelas!

2022-03-10 17:09 UTC, KellyCarvalho commented on src/test/java/CategoryTest.java
> +        assertFalse(categoriesActives.containsAll(categories));
Eu usei desta forma porque os testes usam a lista principal para comparar cada cenário que retorna uma lista com os parâmetros da regra, não enxerguei uma forma de fazer isso sem uma lista global

2022-03-10 20:07 UTC, thaisandre requested changes

2022-03-11 03:13 UTC, mariasantosdev commented on files/database/modelingScript.sql
> +`status` ENUM('ACTIVE','DISABLED'),
poderiamos colocar um valor DEFAULT assim como colocamos no java oque acha? No java colocamos como DISABLED

2022-03-11 03:16 UTC, mariasantosdev commented on files/database/modelingScript.sql
> +`status` ENUM('ACTIVE','DISABLED'),
Poderiamos colocar um valor default assim como no java

2022-03-11 03:22 UTC, mariasantosdev commented on src/test/java/CategoryServiceTest.java
> +                new Category("Programação", "programacao", CategoryStatus.ACTIVE),
[totalmente optional] - poderia fazer o static import desse status, só estou comentando para você saber que existe essa possibilidade

2022-03-11 03:30 UTC, mariasantosdev commented
Nenhum é request change eu acabei clicando errado :crying_cat_face:

2022-03-11 03:32 UTC, mariasantosdev commented
Acho legal seguir a organização dos packages, adicionar packages como category, course, subcategory etc aqui também

![image](https://user-images.githubusercontent.com/75762013/157796743-f7413b7c-72f7-42c1-9245-69d6bcd59cba.png)

2022-03-11 12:39 UTC, mariasantosdev commented on src/test/java/CategoryServiceTest.java
> +        assertTrue(categoriesActives.containsAll(activeCategories));
Existem maneiras mais faceis do que ter que criar duas listas para isso Kelly e seria usando um assert melhor, segue alguns bem bacanas que vi nesse link https://www.baeldung.com/junit-assertions
Se quiser explorar ainda mais dá para dar uma olhada na documentação 
https://junit.org/junit4/javadoc/4.12/org/junit/Assert.html

2022-03-11 12:43 UTC, mariasantosdev commented on src/test/java/CategoryTest.java
> +                new Category("Comunicação", "comunicacao", CategoryStatus.DISABLED)
Pra que criar essas categorias nesse caso? Em todo método de teste você já está dando new na Category e criando os cenários!! Não tem porque essas categorias serem criadas concorda?

2022-03-11 12:52 UTC, KellyCarvalho commented on src/test/java/CategoryTest.java
> +                new Category("Comunicação", "comunicacao", CategoryStatus.DISABLED)
Estava testando algumas listas mas depois que separei os métodos pra um service acabei esquecendo as listas aí

2022-03-11 12:55 UTC, mariasantosdev commented on src/test/java/CourseTest.java
> +                "Tamires", "Curso de Java", "java", subCategory));
mesmo comentário que fiz na CategoryTest....você acabou criando tudo isso mas está dando new no Course dentro de todos os métodos, então porque não deletar isso? deixar somente a Category e a Subcategory aqui pois o curso depende de uma subcategoria e uma subcategoria depende de uma categoria então faz total sentido elas estarem aqui para você não ter que repetir a criação delas em todos os cenários

2022-03-11 12:56 UTC, mariasantosdev commented on src/test/java/CourseTest.java
> +    @ValueSource(ints = {1, 10, 20})
Gostei desses cenários testou muito bem as bordas!!

2022-03-11 13:14 UTC, mariasantosdev commented on src/test/java/CategoryTest.java
> +                new Category("Comunicação", "comunicacao", CategoryStatus.DISABLED)
aah entendi, mas mesmo quando fazemos testes com listas a gente costuma colocar a lista dentro do cenário/método que precisa dela, no ` @BeforeAll` somente coisas que vamos precisar em todos os cenários do teste

2022-03-11 13:26 UTC, KellyCarvalho commented on src/test/java/CsvReaderTest.java
> +    private static Course courseJdk;
ok modifiquei para estar apenas no método pq os objetos possuem dependências

2022-03-11 17:55 UTC, thaisandre approved these changes

2022-03-11 17:56 UTC, thaisandre commented
boa, Kelly! novamente, parabéns! está muito bom!

2022-03-12 02:42 UTC, mariasantosdev approved these changes

2022-03-12 17:13 UTC, merged